<a href="https://colab.research.google.com/github/muzammil002/FYP_Projects/blob/master/Pytorch_example.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch.nn as nn
import numpy as np
import torch

In [2]:
inputs = np.array([[73, 67, 43], 
                   [91, 88, 64], 
                   [87, 134, 58], 
                   [102, 43, 37], 
                   [69, 96, 70], 
                   [74, 66, 43], 
                   [91, 87, 65], 
                   [88, 134, 59], 
                   [101, 44, 37], 
                   [68, 96, 71], 
                   [73, 66, 44], 
                   [92, 87, 64], 
                   [87, 135, 57], 
                   [103, 43, 36], 
                   [68, 97, 70]], 
                  dtype='float32')

# Targets (apples, oranges)
targets = np.array([[56, 70], 
                    [81, 101], 
                    [119, 133], 
                    [22, 37], 
                    [103, 119],
                    [57, 69], 
                    [80, 102], 
                    [118, 132], 
                    [21, 38], 
                    [104, 118], 
                    [57, 69], 
                    [82, 100], 
                    [118, 134], 
                    [20, 38], 
                    [102, 120]], 
                   dtype='float32')

inputs=torch.from_numpy(inputs)
targets=torch.from_numpy(targets)

In [3]:
from torch.utils.data import TensorDataset
from torch.utils.data import DataLoader

train_ds = TensorDataset(inputs, targets)
train_ds[0:3]

batch_size=5

train_dl=DataLoader(train_ds,batch_size,shuffle=True)


In [4]:
for xb,yb in train_dl:
  print(xb)
  print(yb)
  break

tensor([[ 74.,  66.,  43.],
        [101.,  44.,  37.],
        [103.,  43.,  36.],
        [ 73.,  66.,  44.],
        [ 91.,  87.,  65.]])
tensor([[ 57.,  69.],
        [ 21.,  38.],
        [ 20.,  38.],
        [ 57.,  69.],
        [ 80., 102.]])


In [5]:
model=nn.Linear(3,2)
print(model.weight)

Parameter containing:
tensor([[ 0.4401,  0.0876, -0.4660],
        [ 0.4145,  0.3007, -0.0118]], requires_grad=True)


In [6]:
preds=model(inputs)
preds

tensor([[18.1592, 50.3953],
        [18.1331, 63.9235],
        [23.1976, 76.1666],
        [31.6160, 55.2712],
        [ 6.3557, 57.1386],
        [18.5117, 50.5091],
        [17.5795, 63.6111],
        [23.1716, 76.5694],
        [31.2635, 55.1574],
        [ 5.4495, 56.7123],
        [17.6056, 50.0828],
        [18.4856, 64.0374],
        [23.7512, 76.4790],
        [32.5221, 55.6975],
        [ 6.0032, 57.0247]], grad_fn=<AddmmBackward0>)

In [7]:
import torch.nn.functional as F

In [8]:
loss_fn = F.mse_loss

In [9]:
loss = loss_fn(preds,targets)
loss

tensor(3311.6968, grad_fn=<MseLossBackward0>)

In [10]:
opt=torch.optim.SGD(model.parameters(),lr=1e-5)

In [11]:
# Utility function to train the model
def fit(num_epochs, model, loss_fn, opt, train_dl):
    
    # Repeat for given number of epochs
    for epoch in range(num_epochs):
        
        # Train with batches of data
        for xb,yb in train_dl:
            
            # 1. Generate predictions
            pred = model(xb)
            
            # 2. Calculate loss
            loss = loss_fn(pred, yb)
            
            # 3. Compute gradients
            loss.backward()
            
            # 4. Update parameters using gradients
            opt.step()
            
            # 5. Reset the gradients to zero
            opt.zero_grad()
        
        # Print the progress
        if (epoch+1) % 10 == 0:
            print('Epoch [{}/{}], Loss: {:.4f}'.format(epoch+1, num_epochs, loss.item()))

In [12]:
fit(100, model, loss_fn, opt, train_dl)

Epoch [10/100], Loss: 859.5978
Epoch [20/100], Loss: 592.0990
Epoch [30/100], Loss: 440.9514
Epoch [40/100], Loss: 312.4523
Epoch [50/100], Loss: 99.4583
Epoch [60/100], Loss: 69.9194
Epoch [70/100], Loss: 145.3111
Epoch [80/100], Loss: 141.6709
Epoch [90/100], Loss: 103.5742
Epoch [100/100], Loss: 78.2026
