<a href="https://colab.research.google.com/github/muzammil002/FYP_Projects/blob/master/Pytorch_example.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import torch.nn as nn
import numpy as np
import torch

In [7]:
inputs = np.array([[73, 67, 43], 
                   [91, 88, 64], 
                   [87, 134, 58], 
                   [102, 43, 37], 
                   [69, 96, 70], 
                   [74, 66, 43], 
                   [91, 87, 65], 
                   [88, 134, 59], 
                   [101, 44, 37], 
                   [68, 96, 71], 
                   [73, 66, 44], 
                   [92, 87, 64], 
                   [87, 135, 57], 
                   [103, 43, 36], 
                   [68, 97, 70]], 
                  dtype='float32')

# Targets (apples, oranges)
targets = np.array([[56, 70], 
                    [81, 101], 
                    [119, 133], 
                    [22, 37], 
                    [103, 119],
                    [57, 69], 
                    [80, 102], 
                    [118, 132], 
                    [21, 38], 
                    [104, 118], 
                    [57, 69], 
                    [82, 100], 
                    [118, 134], 
                    [20, 38], 
                    [102, 120]], 
                   dtype='float32')

inputs=torch.from_numpy(inputs)
targets=torch.from_numpy(targets)

In [8]:
from torch.utils.data import TensorDataset
from torch.utils.data import DataLoader

train_ds= TensorDataset(inputs, targets)
batch_size=5
train_dl=DataLoader(train_ds,batch_size,shuffle=True)


In [9]:
for xb,yb in train_dl:
  print(xb)
  print(yb)
  break

tensor([[ 68.,  97.,  70.],
        [103.,  43.,  36.],
        [ 87., 135.,  57.],
        [ 69.,  96.,  70.],
        [ 92.,  87.,  64.]])
tensor([[102., 120.],
        [ 20.,  38.],
        [118., 134.],
        [103., 119.],
        [ 82., 100.]])


In [10]:
model=nn.Linear(3,2)
print(model.weight)

Parameter containing:
tensor([[-0.2383,  0.4561, -0.5393],
        [ 0.5710, -0.3239, -0.1425]], requires_grad=True)


In [27]:
preds=model(inputs)
preds

tensor([[-10.5870,  13.5849],
        [-16.6228,  14.0679],
        [  8.5465,  -2.2582],
        [-25.2078,  38.7705],
        [-10.9675,  -1.9393],
        [-11.2814,  14.4797],
        [-17.6182,  14.2492],
        [  7.7690,  -1.8298],
        [-24.5135,  37.8756],
        [-11.2685,  -2.6528],
        [-11.5824,  13.7662],
        [-17.3172,  14.9627],
        [  9.5419,  -2.4396],
        [-24.9068,  39.4840],
        [-10.2731,  -2.8341]], grad_fn=<AddmmBackward0>)

In [13]:
import torch.nn.functional as F

In [16]:
loss_fn = F.mse_loss

In [26]:
loss = loss_fn(preds,targets)
loss

tensor(8494.2344, grad_fn=<MseLossBackward0>)

In [19]:
opt=torch.optim.SGD(model.parameters(),lr=1e-5)

In [24]:
def fit(num_epoch, model, loss_fn, opt, train_dl):
  for epoch in range(num_epoch):
    for xb , yb in train_dl:
      pred=model(xb)
      loss=loss_fn(pred,yb)
      loss.backward()
      opt.step
      opt.zero_grad()
    if (epoch+1) % 10 == 0:
      print('Epoch [{}/{}], Loss: {:.4f}'.format(epoch+1, num_epoch, loss.item()))


In [25]:
fit(100, model, loss_fn, opt, train_dl)

Epoch [10/100], Loss: 5913.5439
Epoch [20/100], Loss: 10741.6260
Epoch [30/100], Loss: 6959.5889
Epoch [40/100], Loss: 7187.4766
Epoch [50/100], Loss: 7445.0557
Epoch [60/100], Loss: 6485.2300
Epoch [70/100], Loss: 9454.2441
Epoch [80/100], Loss: 13087.6543
Epoch [90/100], Loss: 8275.2910
Epoch [100/100], Loss: 12525.1895
